DROP TABLE IF EXISTS ESPECE;

DROP TABLE IF EXISTS EXTRAIRE;

DROP TABLE IF EXISTS PARTICIPER;

DROP TABLE IF EXISTS ECHANTILLION;

DROP TABLE IF EXISTS CAMPAGNE;

DROP TABLE IF EXISTS BUDGET;

DROP TABLE IF EXISTS SEQUENCE;

DROP TABLE IF EXISTS SPECIALISER_EN;

DROP TABLE IF EXISTS NECESSITER;

DROP TABLE IF EXISTS UTILISER;
DROP TABLE IF EXISTS MATERIEL;

DROP TABLE IF EXISTS PLATEFORME;

DROP TABLE IF EXISTS PERSONNEL;


DROP TABLE IF EXISTS HABILITATION;